# Generated by Django 5.2.4 on 2025-08-02 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('related_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_app.schedule_model')),
            ],
        ),
    ]
