# Generated by Django 5.2.4 on 2025-08-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirymodel',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquirymodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
