# Generated by Django 5.2.4 on 2025-08-03 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms_and_conditions', models.TextField()),
                ('package_photo', models.JSONField(default=list)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_app.city_model')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='country_app.city_model')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_title', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('schedule_description', models.TextField()),
                ('schedule_photo', models.JSONField(default=list)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tour_app.tour_model')),
            ],
        ),
    ]
